### PR TITLE
[SD-1392] Saved search couldn't be validated for multiple indexes

### PR DESCRIPTION
**Pull request by akintolga**

### CODE REVIEW

**Comment by amagdas** [comment]
Is there a way we can test this?

**Comment by amagdas** [comment]
Missing tests...

**Comment by akintolga** [comment]
There are some behave tests are already in place on features/saved-searches.feature. 
Let me know if you think some unit tests are missing or if you think the behave test doesn't cover all scenarios?

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
