### PR TITLE
(fix) Fixing notifications for lock and unique name permissions.

### PR DESCRIPTION
**Pull request by mdhaman**
SD-1333
SD-1320

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
fixed the behave errors.

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
