### PR TITLE
chore(requirements): freeze behave dependency

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by actionless** [comment]
i have no clue why previous build was failed -- output is truncated

**Comment by petrjasek** [comment]
you can get the [full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/49741468/log.txt)

**Comment by actionless** [comment]
```
    Then we get content expiry 10        # features/steps/steps.py:1036 0.000s
      Assertion Failed: 0 != 1
      Captured logging:
      INFO:elasticsearch:DELETE http://localhost:9200/sptest/archive/_query [status:200 request:0.002s]
      INFO:elasticsearch:DELETE http://localhost:9200/sptest/archive/_query [status:200 request:0.002s]
      INFO:elasticsearch:DELETE http://localhost:9200/sptest/archive/_query [status:200 request:0.003s]
      INFO:elasticsearch:PUT http://localhost:9200/sptest/archive/testid1 [status:201 request:0.003s]
      INFO:elasticsearch:POST http://localhost:9200/sptest/_refresh [status:200 request:0.006s]
      INFO:superdesk.notification:pushing event media_archive ({"created": 1})
      INFO:elasticsearch:GET http://localhost:9200/sptest/archive/testid1 [status:200 request:0.001s]
      INFO:superdesk.notification:pushing event activity ({"_dest": {}})
      INFO:elasticsearch:GET http://localhost:9200/sptest/archive/testid1 [status:200 request:0.001s]
```

that not seems to be related to any of those testing stuff

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
