### PR TITLE
fix(ingest): remove only 100 items at a time

### PR DESCRIPTION
**Pull request by petrjasek**
+ workaround for eve serialization issue affecting `is_closed`

SD-1125

### CODE REVIEW

**Comment by amagdas** [comment]
Should we decrease the period for the job? Instead of 10 min, maybe 2-3?
If not, :+1:

**Comment by petrjasek** [comment]
I think 100 per 10m is enough for aap (ingesting <10k in a day), so atm I would keep it

**Comment by amagdas** [comment]
Sounds good :+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
