### PR TITLE
(fix)privileges: Fixing the unlock and lock of content.

### PR DESCRIPTION
**Pull request by mdhaman**
Its related to the JIRA [SD-1333]  

- [x] Modifying the API for lock/unlock.
- [x] Behave tests lock/unlock.

### CODE REVIEW

**Comment by mdhaman** [comment]
@petrjasek, @amagdas , @mugurrus can you please review at this PR?

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
