### PR TITLE
add python env

### PR DESCRIPTION
**Pull request by cybernet**
!/usr/bin/env python

### CODE REVIEW

**Comment by petrjasek** [comment]
why add it into apps?

**Comment by cybernet** [comment]
i had some free time :) / i don't "speak" pyhton, btw :dancers:

**Comment by petrjasek** [comment]
:smile:

**Comment by cybernet** [comment]
its on my wish list... any tips ?:D

**Comment by petrjasek** [comment]
I think you can't go wrong with [hitchhiker's guide](https://python-guide.readthedocs.org/en/latest/)

**Comment by petrjasek** [comment]
thx man, but there is no use imo

**Pull request closed without merging**
