### PR TITLE
[SD-1511] Add events for desk/stage changes

### PR DESCRIPTION
**Pull request by marwoodandrew**
Send events/notifications on changes to desks/stages.

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
It would have been better to add Desk Name and Stage Name instead of `_id` as `_id` is not understandable to user.

**Comment by marwoodandrew** [comment]
I though that on the client they are going to keep some sort of map of the desk/stages belonging to the user,so could use the _id to work out if there have been relevant changes. The stage names are not unique in the system so maybe not that usefull

**Comment by ioanpocol** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
@sivakuna-aap @marwoodandrew right there is a list of user desks/stages on client side

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
